### ISSUE TITLE
Squashed Track button

### ISSUE THREAD

**Issue by ghost** [klermor/KnownTracks#1]
First off thank you so much for writing this known plugin!
However I have found a few issues.

The track button is a bit squashed compared to the rest.

http://i.imgur.com/ny9oDgt.png

**Comment by klermor** [comment]
Hi Mark
thank you for your feedback. 
you should have this:
![tracks_button](https://cloud.githubusercontent.com/assets/1436763/8699402/88296b62-2b05-11e5-8a96-2a72b70149d8.png)
have you this 

```
.icon-globe {
  background-position: -336px -144px;
}
```

in {root_known}/external/bootstrap/assets/css/bootstrap.css file ?

**Comment by ghost** [comment]
I'm afraid I don't have that.
I am using the latest git version of Known not one of the releases if that makes any difference.

The only 'globe' I have is -

<code>.glyphicon-globe:before {
  content: "\e135";
}
</code>

I have added your snippet and the globe you have still does not show in any of the themes.

**Comment by danito** [comment]
I've the same problem. The icon didn't show up.
I changed the file IdnoPlugins/Tracks/templates/default/entity/Tracks/icon.tpl.php to

``` php
<i class="fa fa-globe"></i>
```

I think the glyphicons aren't used with BS3 anymore but http://fortawesome.github.io/Font-Awesome/icon/globe/

**Comment by ghost** [comment]
Looking good and round now , thanks!
