### ISSUE TITLE
New Track details page size

### ISSUE THREAD

**Issue by ghost** [klermor/KnownTracks#2]
When using the new track details page on a desktop browser the dimensions seem restricted to a mobile browser size.

http://i.imgur.com/YukdZZf.png

**Comment by klermor** [comment]
I can not reproduce this with firefox and chromium (linux).
What is your browser ?

**Comment by ghost** [comment]
I am using Iceweasel 31.8.0 on a Debian Wheezy based distro running on an ARM device.
My wife is running a later version , I will check it on her PC later.

**Comment by danito** [comment]
Hi,
I've the same, I guess your template is not Bootstrap 3 compatible.
The classes in https://github.com/klermor/KnownTracks/blob/master/templates/default/entity/Tracks/edit.tpl.php#L30 have still span8 offset2 which should be col-8 col-md-offset-2 for BS3.

**Comment by klermor** [comment]
Yes indeed. The plugin version is for  Known 0.7.8.5.1 "Makeba" release. 
I'll work on it after my vacation

**Comment by ghost** [comment]
Editing is now full width , thanks , hope you had a nice holiday.

**Comment by klermor** [comment]
Thx Mark. Yes, I had a great holiday :)
