### ISSUE TITLE
Metric vs Imperial

### ISSUE THREAD

**Issue by ghost** [klermor/KnownTracks#3]
Is it possible to have metric output for the track details below the graph - distance , duration , pace and elevation , etc.
Thanks.

**Comment by klermor** [comment]
yes of course (but not yet for graph elevation... soon)
site configuration > Tracks
![tracks_metric](https://cloud.githubusercontent.com/assets/1436763/8699993/978537e0-2b09-11e5-9f61-9eb77f67c195.png)

**Comment by ghost** [comment]
OMG , I didn't even see that in the configuration section.
Sorry.
