### ISSUE TITLE
Post Privacy Settings don't change on update

### ISSUE THREAD

**Issue by ghost** [klermor/KnownTracks#4]
So I was going through my posts manually changing them from Public to Members-Only so that I can switch my site from Members-Only to Public when I noticed that some post types do not update.

'Tracks' do not update and remain Public.

I had the same issue with 'Locations'

https://github.com/idno/Known/issues/1012

@benwerd has fixed it in 

https://github.com/idno/Known/commit/3e36b2313cee889a8cb3280497747bbd12ee2874

**Comment by klermor** [comment]
Thx Mark and Ben
fixed: https://github.com/klermor/KnownTracks/commit/a6fd670b6dbfa3c6501578afdf8f5284663a4346

**Comment by ghost** [comment]
Thanks @klermor , working perfectly for me.
I feel so humble having my name in a changelog too!
