### ISSUE TITLE
Error when creating a track

### ISSUE THREAD

**Issue by danito** [klermor/KnownTracks#6]
Hi,
after hitting publish nothing happens and in the logs I get this error : 
PHP Warning:  Missing argument 2 for Idno\Core\Template::drawSyndication(), called in /var/www/virtual/nxd4n/html/IdnoPlugins/Tracks/templates/default/entity/Tracks/edit.tpl.php on line 92 and defined in /var/www/virtual/nxd4n/html/Idno/Core/Template.php on line 109, referer: https://nxd4n.nixekinder.be/

In the DB, I can see that I've some entities IdnoPlugins\Tracks\Tracks so when try to access the url directly, I get this in the logs : 
 PHP Notice:  Undefined variable: object in /var/www/virtual/nxd4n/html/templates/defau
lt/shell.tpl.php on line 167

Seems that Tracks is not compatible with latest Known version

**Comment by klermor** [comment]
thx for your feedback. i'll do it as soon as i can.
Merci danito

**Comment by klermor** [comment]
'make it compatible with known 0.9' check !

**Comment by danito** [comment]
Désolé,
I did a git pull, but I get still the follwing : 
mod_fcgid: stderr: PHP Notice:  Undefined variable: object in /var/www/virtual/nxd4n/html/templates/default/shell.tpl.php on line 167

``` php
       if ($currentPage->isPermalink()) {
            /* @var \Idno\Common\Entity $object */
            if ($object instanceof \Idno\Common\Entity) {  // ligne 167

                if ($creator = $object->getOwner()) {
                    ?>
                    <meta name="DC.creator" content="<?= htmlentities($creator->getTitle()) ?>"><?php

```

And nothing shows up. 
Any idea?
