### ISSUE TITLE
Mixed content warning

### ISSUE THREAD

**Issue by ghost** [klermor/KnownTracks#7]
I run a secured HTTPS site but when I have a track published I see a mixed content warning due to the image tiles from http://*.tile.openstreetmap.org/ being delivered insecurely.

Is there an option to have these delivered via HTTPS too ?

I have checked and the openstreetmap site is available via HTTP and HTTPS.

Thanks.
Mark.

**Comment by danito** [comment]
Hi,
my guess is that we can change http to https in this function: https://github.com/klermor/KnownTracks/blob/master/Tracks/Tracks.php#L125

**Comment by ghost** [comment]
Thanks @danito , I have made the edits locally and it is working as expected with no mixed content warning.
Could this be made to automatically detect whether the site is HTTP or HTTPS ?

**Comment by danito** [comment]
maybe add something like after line 125

```
$https = "http";
if (isset($_SERVER['HTTPS'])) {
   $https = "https";
}
```

and change http to {$https} in $map = "L.tileLayer('**http**://otile{s}..."
But from http://stackoverflow.com/questions/4042962/php-http-or-https it seems that checking if https is not so straight forward

**Comment by ghost** [comment]
Updated the file with your code and it is still working with no mixed content warnings.
Looks like the checking seems to work correctly.
Thanks for all your help with this @danito
